import type { Metadata } from 'next';
import { inter } from './font';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased overflow-x-hidden text-gray-800`}>{children}</body>
        </html>
    );
}
